name: 'Schemathesis'
description: 'Property-based API testing with Schemathesis'
author: 'Dmitry Dygalo <@Stranger6667> | Schemathesis.io'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  schema:
    description: 'API schema location (URL or file path) '
    required: true
  base-url:
    description: 'Override base URL '
    required: false
  checks:
    description: 'Validation checks to run (default: all)'
    required: false
    default: 'all'
  wait-for-schema:
    description: 'Schema availability timeout in seconds'
    required: false
    default: '2'
  max-examples:
    description: 'Maximum test cases per API operation'
    required: false
    default: '100'
  version:
    description: 'Schemathesis version (default: latest)'
    required: false
    default: 'latest'
  hooks:
    description: 'Python module path for hooks'
    required: false
  config-file:
    description: 'Path to a `schemathesis.toml` configuration file'
    required: false
  args:
    description: 'Additional CLI arguments'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - uses: astral-sh/setup-uv@v7
      with:
        version: ">=0.5.0"
    - run: |
        if [ ${{ inputs.version }} == "latest" ] ; then
          uv tool install "schemathesis>=4.0,<5.0"
        else
          uv tool install schemathesis==${{ inputs.version }}
        fi
      shell: bash
    - run: |
        set -euo pipefail

        SCHEMA='${{ inputs.schema }}'
        CHECKS='${{ inputs.checks }}'
        MAX_EXAMPLES='${{ inputs.max-examples }}'
        CONFIG_FILE='${{ inputs.config-file }}'
        ARGS='${{ inputs.args }}'

        eval "ARGS_ARRAY=($ARGS)"

        CMD=(schemathesis)
        if [[ -n "$CONFIG_FILE" ]]; then
          CMD+=(--config-file="$CONFIG_FILE")
        fi

        CMD+=(run
          "$SCHEMA"
          --generation-database=":memory:"
          --max-examples="$MAX_EXAMPLES"
          --checks="$CHECKS"
        )

        CMD+=("${ARGS_ARRAY[@]}")

        "${CMD[@]}"
      shell: bash
      env:
        SCHEMATHESIS_BASE_URL: ${{ inputs.base-url }}
        SCHEMATHESIS_WAIT_FOR_SCHEMA: ${{ inputs.wait-for-schema }}
        SCHEMATHESIS_HOOKS: ${{ inputs.hooks }}
