name: 'Schemathesis'
description: 'Property-based API testing with Schemathesis'
author: 'Dmitry Dygalo <@Stranger6667> | Schemathesis.io'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  schema:
    description: 'API schema location (URL or file path) '
    required: true
  base-url:
    description: 'Override base URL '
    required: false
  checks:
    description: 'Validation checks to run (default: all)'
    required: false
    default: 'all'
  wait-for-schema:
    description: 'Schema availability timeout in seconds'
    required: false
    default: '2'
  max-examples:
    description: 'Maximum test cases per API operation'
    required: false
    default: '100'
  version:
    description: 'Schemathesis version (default: latest)'
    required: false
    default: 'latest'
  hooks:
    description: 'Python module path for hooks'
    required: false
  args:
    description: 'Additional CLI arguments'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - uses: astral-sh/setup-uv@v6
      with:
        version: ">=0.5.0"
    - run: |
        if [ ${{ inputs.version }} == "latest" ] ; then
          uv tool install schemathesis
        else
          uv tool install schemathesis==${{ inputs.version }}
        fi
      shell: bash
    - run: |
        schemathesis run \
          ${{ inputs.schema }} \
          --generation-database=:memory: \
          --max-examples=${{ inputs.max-examples }} \
          --checks=${{ inputs.checks }} \
          ${{ inputs.args }} \
      shell: bash
      env:
        SCHEMATHESIS_BASE_URL: ${{ inputs.base-url }}
        SCHEMATHESIS_WAIT_FOR_SCHEMA: ${{ inputs.wait-for-schema }}
        SCHEMATHESIS_HOOKS: ${{ inputs.hooks }}
